title: Rennan C. Lima
position: MSc. Student
affiliation: UFMG
email: rennancordeiro (at) dcc.ufmg.br
keywords: information retrieval
google_scholar: https://scholar.google.com/citations?user=CIopUhUAAAAJ&hl=en
github_link: https://github.com/rennancl
twitter: https://twitter.com/clrennan
linkedin: https://www.linkedin.com/in/rennan-cordeiro-093b66140/
avatar: ./assets/img/me.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://rennancl.github.io/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
